### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by Cahllagerfeld** [Cahllagerfeld/setup-stargate#1]

**Comment by Agrover112** [comment]
Hi I would like to work on this issue. Being a python user IDK what the installation instructions would be and what the project exactly does as of now for the README.md  @Cahllagerfeld

**Comment by Cahllagerfeld** [comment]
> 
> 
> Hi I would like to work on this issue. Being a python user IDK what the installation instructions would be and what the project exactly does as of now for the README.md @Cahllagerfeld

For now its fine, if you just create it 👍 
I'll add the content later, as its currently in a pre-release phase

**Comment by Cahllagerfeld** [comment]
closed with #8
